### ISSUE TITLE
Add support for setting the Storage Class of an object you upload

### ISSUE THREAD

**Issue by gpapin** [paulhammond/s3simple#3]
It would be great to have the ability to set the storage class as an argument of this script so you can minimize the cost of using S3.

Basically all we need is to setup the `x-amz-storage-class` request header on the `PUT` command

More information about it here
http://docs.aws.amazon.com/AmazonS3/latest/dev/SetStoClsOfObjUploaded.html

**Comment by paulhammond** [comment]
This is a simple script so I'd encourage you to make a copy and edit it (probably [line 47](https://github.com/paulhammond/s3simple/blob/70486bfebc83884d2fee66e856c9a9c752717dfb/s3simple#L47)) until it does what you need.

I'm happy to take a pull request that adds this support, but I'm not going to be making these changes for you so I'm going to close this issue out. Sorry!
