### ISSUE TITLE
Having trouble with endpoints

### ISSUE THREAD

**Issue by twekberg** [paulhammond/s3simple#5]
When I try to get a file with the AWS credentials exports set I get this error:

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>dlmp-oltg-data.s3.amazonaws.com</Endpoint><Bucket>dlmp-oltg-data</Bucket><RequestId>J6PHT3BQ1M16WQPB</RequestId><HostId>a25dkSf+MfTKjZDflgi4PvbERAtKnuf3wJj5wJwpvWlISxHCjSB0F9UkPxmHWMx77g8QF+k+GXk=</HostId></Error>t

Not sure how to proceed.

**Comment by paulhammond** [comment]
Hi!

This script is really really old and used to use "path-style" URLs, which were [deprecated by AWS in 2020](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/). I've just pushed 7d5e11a1b6f7fff714408cf2f5670084aa0e4ab1 which uses "virtual hosted" urls which I think should fix your problem.

If not, the easiest fix is probably to copy the file, and edit [line 74](https://github.com/paulhammond/s3simple/blob/70486bfebc83884d2fee66e856c9a9c752717dfb/s3simple#L74) until it works for you. You might need to add `endpoint.` into the URL, for example.

Hope this is helpful!

**Comment by paulhammond** [comment]
It's also possible that the problem here is the [deprecation of S3 Signature V2](https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/) which also affects any buckets created since 2020. If so you'll probably get an error message saying as such. I'm reopening this to see if that's the problem.

**Comment by twekberg** [comment]
I figured out that the problem was using the wrong region in the endpoint. I fixed my version to do that. I also wrote another script that grabs the default region from ~/.aws/config and the 2 AWS settings from a specified section in ~/.aws/credentials, and calls a modified version of your script. Feel free that take that and my changes. I work for the state of Washington so all of the stuff I write is free. I had to tack on a .txt extension to the filenames to paste them here.

[s3_simple_transfer.sh.txt](https://github.com/paulhammond/s3simple/files/9528995/s3_simple_transfer.sh.txt)
[aws_transfer.txt](https://github.com/paulhammond/s3simple/files/9528997/aws_transfer.txt)

**Comment by paulhammond** [comment]
I'm glad you got it working - and thanks for sharing your changes!

I think they might be too specific to merge into main but if I'm wrong and anyone else is reading this and thinks they're useful please leave a comment so I can reconsider.

**Comment by paulhammond** [comment]
It looks like someone else wanted region support so it's getting implemented - see #6 for details.
